controldeamon:
    ip: 127.0.0.1
    port: 8080
    type: client                #clent and server are only allowed
    protocol: tcp               #tcp udp websocket are only allowed
    name: cntrldeamon           #Do not chnage this name
inputdeamon:
    ip:'' 
    port: 8090
    type: server                #clent and server are only allowed
    protocol: tcp
    name: inpdeamon             #Do not chnage this name
outputdeamon:
    ip: 127.0.0.1
    port: 8100
    type: server               #clent and server are only allowed
    protocol: tcp       #tcp udp websocket are only allowed
    name: oudeamon             #Do not chnage this name
metadata:
    deviceparameters: -p 100 -q 10000
    programparameters: -t 100 -y 10000
